version: '3.3'
services:
  watford-pdf:
    container_name: Watford-PDF-Ultra-Lite-Security
    image: frooodle/s-pdf:latest-ultra-lite
    deploy:
      resources:
        limits:
          memory: 1G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/v1/info/status | grep -q 'UP' && curl -fL http://localhost:8080/ | grep -q 'Please sign in'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - 8080:8080
    volumes:
      - /watford/latest/data:/usr/share/tesseract-ocr/5/tessdata:rw
      - /watford/latest/config:/configs:rw
      - /watford/latest/logs:/logs:rw
    environment:
      DOCKER_ENABLE_SECURITY: "true"
      SECURITY_ENABLELOGIN: "true"
      SYSTEM_DEFAULTLOCALE: en_US
      UI_APPNAME: Watford-PDF-Lite
      UI_HOMEDESCRIPTION: Demo site for Watford-PDF-Lite Latest with Security
      UI_APPNAMENAVBAR: Watford-PDF-Lite Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
    restart: on-failure:5
