# Build jbig2enc in a separate stage
FROM bellsoft/liberica-openjdk-debian:17

ARG VERSION_TAG

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libreoffice-core \
        libreoffice-common \
        libreoffice-writer \
        libreoffice-calc \
        libreoffice-impress \
        unoconv && \
    rm -rf /var/lib/apt/lists/*


# Set Environment Variables
ENV DOCKER_ENABLE_SECURITY=false \
    HOME=/home/watfordpdfuser \
    VERSION_TAG=$VERSION_TAG \
    JAVA_TOOL_OPTIONS="$JAVA_TOOL_OPTIONS -XX:MaxRAMPercentage=75"
#	PUID=1000 \
#   PGID=1000 \
#   UMASK=022 \

# Create user and group
#RUN groupadd -g $PGID watfordpdfgroup && \
#    useradd -u $PUID -g watfordpdfgroup -s /bin/sh watfordpdfuser && \
#    mkdir -p $HOME && chown watfordpdfuser:watfordpdfgroup $HOME

# Set up necessary directories and permissions
RUN mkdir -p /scripts /usr/share/fonts/opentype/noto /configs /customFiles /logs /pipeline /pipeline/defaultWebUIConfigs  /pipeline/watchedFolders /pipeline/finishedFolders

#    chown -R watfordpdfuser:watfordpdfgroup /usr/share/fonts/opentype/noto /configs /customFiles

# Copy necessary files
COPY ./scripts/download-security-jar.sh /scripts/download-security-jar.sh
COPY ./scripts/init-without-ocr.sh /scripts/init-without-ocr.sh
COPY ./pipeline/ /pipeline/
COPY src/main/resources/static/fonts/*.ttf /usr/share/fonts/opentype/noto/
COPY src/main/resources/static/fonts/*.otf /usr/share/fonts/opentype/noto/
COPY build/libs/*.jar app.jar

# Set font cache and permissions
RUN fc-cache -f -v && \
chmod +x /scripts/init-without-ocr.sh && \
chmod +x /scripts/download-security-jar.sh


#    chown watfordpdfuser:watfordpdfgroup /app.jar




# Expose the application port
EXPOSE 8080

# Set environment variables
ENV ENDPOINTS_GROUPS_TO_REMOVE=Python,OpenCV,OCRmyPDF
ENV DOCKER_ENABLE_SECURITY=false

# Run the application
#USER watfordpdfuser
ENTRYPOINT ["/scripts/init-without-ocr.sh"]
CMD ["java", "-Dfile.encoding=UTF-8", "-jar", "/app.jar"]
